#+TITLE: Notes from Underground
CLOSED: [2026-01-03 Sat 19:29]

#+begin_quote
And enter my house bold and free,
To become its full mistress!
#+end_quote

* I. Underground

Can a man possessing consciousness ever really respect himself?

And all as a result of boredom, gentlemen, sheer boredom; I was overcome by inertia. You see, the direct, legitimate, immediate result of consciousness is inertia, that is, the conscious sitting idly by with one’s arms folded.

But man is so partial to systems and abstract conclusions that he’s ready to distort the truth intentionally, ready to deny everything that he himself has ever seen and heard, merely in order to justify his own logic.

Why, I, for example, wouldn’t be surprised in the least, if, suddenly, for no reason at all, in the midst of this future, universal rationalism, some gentleman with an offensive, rather, a retrograde and derisive expression on his face were to stand up, put his hands on his hips, and declare to us all: "How about it, gentlemen, what if we knock over all this rationalism with one swift kick for the sole purpose of sending all these logarithms to hell, so that once again we can live according to our own stupid will!" But that wouldn’t matter either; what’s so annoying is that he would undoubtedly find some followers; such is the way man is made.

You repeat that an enlightened and cultured man, in a word, man as he will be in the future, cannot knowingly desire something disadvantageous to himself, and that this is pure mathematics. I agree with you: it really is mathematics. But I repeat for the one-hundredth time, there is one case, only one, when a man may intentionally, consciously desire even something harmful to himself, something stupid, even very stupid, namely: in order to have the right to desire something even very stupid and not be bound by an obligation to desire only what's smart.

Because in any case it preserves for us what’s most important and precious, that is, our personality and our individuality.

But man is a frivolous and unseemly creature and perhaps, like a chess player, he loves only the process of achieving his goal, and not the goal itself.

I agree that two times two makes four is a splendid thing; but if we’re going to lavish praise, then two times two makes five is sometimes also a very charming little thing.

I’m convinced that man will never renounce real suffering, that is, destruction and chaos. After all, suffering is the sole cause of consciousness. Although I stated earlier that in my opinion consciousness is man’s greatest misfortune, still I know that man loves it and would not exchange it for any other sort of satisfaction. Consciousness, for example, is infinitely higher than two times two. Of course, after two times two, there’s nothing left, not merely nothing to do, but nothing to learn.

Destroy my desires, eradicate my ideals, show me something better and I’ll follow you. You may say, perhaps, that it’s not worth getting involved; but, in that case, I’ll say the same thing in reply. We’re having a serious discussion; if you don’t grant me your attention, I won’t grovel for it. I still have my underground.

Even though I said that I envy the normal man to the point of exasperation, I still wouldn’t want to be him under the circumstances in which I see him (although I still won’t keep from envying him. No, no, in any case the underground is more advantageous!)

Is it possible to be absolutely honest even with one’s own self and not to fear the whole truth?

I have hundreds of such memories; but at times a single one emerges from those hundreds and oppresses me. For some reason I believe that if I write it down I can get rid of it. Why not try? 

Lastly, I’m bored, and I never do anything. Writing things down actually seems like work. They say that work makes a man become good and honest. Well, at least there’s a chance.

* II. Apropos of Wet Snow

In the end I myself couldn’t stand it: as the years went by, my need for people, for friends, increased. I made several attempts to get closer to some of them; but these attempts always turned out to be unnatural and ended of their own accord.

I frightened him with my passionate friendship, and I reduced him to tears and convulsions. He was a naive and giving soul, but as soon as he’d surrendered himself to me totally, I began to despise him and reject him immediately—as if I only needed to achieve a victory over him, merely to subjugate him.


Of course, it would have been better not to go at all. But that was no longer possible; once I began to feel drawn to something, I plunged right in, head first. I’d have reproached myself for the rest of my life: "So, you retreated, you retreated before reality, you retreated!"

Oh, if you only knew what thoughts and feelings I’m capable of, and how cultured I really am!

Now I’d suddenly realized starkly how absurd, how revolting as a spider, was the idea of debauchery, which, without love, crudely and shamelessly begins precisely at the point where genuine love is consummated.

There’s something else, Liza. Man only likes to count his troubles; he doesn’t calculate his happiness.

No one, no one at all has to know what goes on between a husband and wife, if they love each other. However their quarrel ends, they should never call in either one of their mothers to act as judge or to hear complaints about the other one. They must act as their own judges. Love is God’s mystery and should be hidden from other people’s eyes, no matter what happens.

No, Liza, I think you must first learn how to live by yourself, and only afterward blame others.

Yet, I didn’t understand that she was intentionally disguising her feelings with sarcasm; that was usually the last resort of people who are timid and chaste of heart, whose souls have been coarsely and impudently invaded; and who, until the last moment, refuse to yield out of pride and are afraid to express their own feelings to you.

No one, absolutely no one in the whole world, will ever come to visit you; your name will disappear from the face of the earth, just as if you’d never been born and had never existed.

The poor little thing, she’d saved this student’s letter as a treasure and had run to fetch this one treasure of hers, not wanting me to leave without knowing that she too was the object of sincere, honest love, and that someone exists who had spoken to her respectfully.

The true story, as they say, is no reproach to an honest young man.

"Liza", I’d say, "Do you really think that I haven’t noticed your love? I’ve seen everything. I guessed, but dared not be first to make a claim on your heart because I had such influence over you, and because I was afraid you might deliberately force yourself to respond to my love out of gratitude, that you might forcibly evoke within yourself a feeling that didn’t really exist. No, I didn’t want that because it would be... despotism. ... It would be indelicate."

If all this faded to bring me back to my senses and I continued to rebel, he’d suddenly begin to sigh while staring at me. He’d sigh heavily and deeply, as if trying to measure with each sigh the depth of my moral decline.

It was the cynicism, the cynicism of my words that crushed her.

Should the world go to hell, or should I go without my tea? I say, let the world go to hell as long as I can always have my tea.

They won’t let me... I can’t be... good!

And so, I’m convinced to this day that it was precisely because I felt too ashamed to look at her, that another feeling was suddenly kindled and burst into flame in my heart—the feeling of domination and possession.

On the other hand, she fully understood that I was a despicable man, and, most important, that I was incapable of loving her.

In the first place, I could no longer love because, I repeat, for me love meant tyrannizing and demonstrating my moral superiority. All my life I could never even conceive of any other kind of love, and I’ve now reached the point that I sometimes think that love consists precisely in a voluntary gift by the beloved person of the right to tyrannize over him.
