#+TITLE:Stop Musturbating
#+OPTIONS: toc:nil

#+begin_note
This is an excerpt from the third chapter of the book "Feeling Good" by Dr. David D. Burns.
#+end_note

Statements such as "I /should/ do this" or "I /must/ do this" when used for motivation leads to one feeling pressured or resentful. By trying to motivate oneself in this way, one ends up feeling apathetic and unmotivated, this phenomenon is called "musturbation" by Albert Ellis.

These statements generate a lot of unnecessary emotional turmoil in one's daily life leading to self-loathing, shame or guilt. When other people fall short of expectations, one feels bitter and self-righteous.

Change expectations to approximate reality, stop /musturbating/.

* Cognititive Distortions

1. /All-or-Nothing/ Thinking

   It forms the basis for perfectionism, causing one to fear any mistake or imperfection to avoid seeing oneself as a loser, or feeling inadequate or worthless.

2. /Overgeneralization/

   Seeing a single negative event as a never-ending pattern of defeat. The pain of rejection is generated almost entirely from overgeneralization. In its absence, a personal affront is temporarily disappointing but /cannot/ be seriously disturbing.

3. /Mental Filter/

   When one's depressed, one wears a pair of eyeglasses with special lenses that filter out anything positive, allowing only the negative to enter the conscious mind.

4. /Disqualifying the Positive/

   A spectacular mental illusion is the persistent tendency to transform neutral or positive experiences into negative ones. An example of this is defending the negative thoughts or disqualifying one's compliment as insincere.

5. /Jumping to Conclusions/

   Making the assumption that other people are looking down on you and being so convinced of the fact that one doesn't even bother verifying it. This self-defeating behavior of imagining negative scenarios might act as a self-fulfilling prophecy and can set one up for negative interactions when none exists.

6. /Binocular Trick/

   When one's blowing things out of proportion or shrinking them; Magnifying when looking at own errors, fears or imperfections and exaggerating their importance; Minimizing when thinking about one's strengths to make them seem small and unimportant leading to feelings of inferiority.

7. /Emotional Reasoning/

   Taking the emotions as evidence for truth. "Because I feel like something, I /am/ that". This reasoning is misleading because one's feelings reflect thoughts and beliefs (when distorted) that might be invalid. Never let the negative feelings guide your actions.

8. /Should Statements/

   Stop "musturbating".

9. /Labeling and Mislabeling/

   Personal labeling such as /"I'm a..."/ leads to creating a completely negative self-image based on errors. It's an extreme form of overgeneralization. And mislabeling other people with inaccurate and emotionally loaded words can generate hostility.

10. /Personalization/

    Assuming responsibility for a negative without any basis for doing so. Arbitrarily conculding that the circumstances were one's fault or reflected one's inadequacy, even when one's not responsible for them, leading to crippling guilt. Confusing /influence/ with /control/.
   
